name = "vault-gold"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "vaultgold-accounts"
database_id = "75b65b4b-664e-4375-97d0-e7e7a611ea95"
